# Generated by Django 6.0.6 on 2026-07-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='time_out',
            new_name='due_time',
        ),
    ]
